# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    # gmsh requires the no X Windows version for CI linux
    post_install:
      - pip install -i https://gmsh.info/python-packages-dev-nox --force-reinstall gmsh==4.11.1.dev1+nox

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Default is HTML
# formats: all

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
