# version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv 0.6.17
      - asdf global uv 0.6.17
      - uv python install 3.13
    create_environment:
      - uv venv -p 3.13
    install:
      - uv sync --locked --no-default-groups --group docs --no-install-package gmsh
      - uv pip install --index https://gmsh.info/python-packages-dev-nox "gmsh<4.13.2"
    build:
      html:
        - uv run sphinx-build -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
