[tool.poetry]
name = "planestress"
version = "0.0.3"
description = "A python package for plane stress analysis using the finite element method."
license = "MIT"
authors = [
    "Robbie van Leeuwen <robbie.vanleeuwen@gmail.com>",
]
maintainers = [
    "Robbie van Leeuwen <robbie.vanleeuwen@gmail.com>",
]
readme = "README.md"
homepage = "https://github.com/robbievanleeuwen/plane-stress"
repository = "https://github.com/robbievanleeuwen/plane-stress"
documentation = "https://plane-stress.readthedocs.io"
keywords = [
    "plane-stress",
    "structural-engineering",
    "finite-element-analysis",
    "computational-mechanics",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Scientific/Engineering",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
packages = [
    { include = "planestress", from = "src" },
    { include = "src/planestress/py.typed" },
]
include = []

[tool.poetry.urls]
Changelog = "https://github.com/robbievanleeuwen/plane-stress/releases"
"Bug Tracker" = "https://github.com/robbievanleeuwen/plane-stress/issues"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
numpy = "^1.25.2"  # numba requires numpy <1.26
scipy = "^1.11.3"
matplotlib = "^3.8.0"
shapely = "^2.0.1"
triangle = "^20230923"
rich = "^13.6.0"
click = "^8.1.7"
numba = "^0.58.0"
pypardiso = { version = "^0.4.2", optional = true }

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
coverage = { extras = ["toml"], version = "^7.3.2" }
darglint = "^1.8.1"
flake8 = "^6.1.0"
flake8-bugbear = "^23.9.16"
flake8-docstrings = "^1.7.0"
flake8-pytest-style = "^1.7.2"
flake8-rst-docstrings = "^0.3.0"
furo = "^2023.9.10"
ipykernel = "^6.25.2"
ipython = "^8.16.1"
ipywidgets = "^8.1.1"
isort = "^5.12.0"
mypy ="^1.6.0"
nbconvert = "^7.9.2"
nbsphinx = "^0.9.3"
notebook = "^7.0.4"
pep8-naming = "^0.13.3"
pre-commit = "^3.4.0"
pre-commit-hooks = "^4.5.0"
Pygments = "^2.16.1"
pytest = "^7.4.2"
pytest-benchmark = { extras = ["histogram"], version = "^4.0.0" }
pytest-check = "^2.2.2"
pyupgrade = "^3.15.0"
sphinx = "^7.2.6"
sphinx-autobuild = "^2021.3.14"
sphinx-click = "^5.0.1"
sphinx-copybutton = "^0.5.2"
sphinxext-opengraph = "^0.8.2"

[tool.poetry.extras]
pardiso = ["pypardiso"]

[tool.poetry.scripts]
planestress = "planestress.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["planestress", "tests"]
omit = ["*/benchmarks/*"]

[tool.coverage.report]
show_missing = true

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.mypy]
strict = true
# output formatting
pretty = true
show_column_numbers = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "mpl_toolkits.*",
    "numba.*",
    "pypardiso.*",
    "scipy.*",
    "shapely.*",
    "triangle.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
markers = [
    "benchmark_suite: entire benchmark test suite (select with '-m benchmark_suite')",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
