blank_issues_enabled: false
contact_links:
  - name: "💬 Discussions"
    url: https://github.com/robbievanleeuwen/plane-stress/discussions
    about: |
      Ask questions about using planestress, planestress's features and roadmap, or get support and feedback for your usage of sectionproperties.
